// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        (unknown)
// source: ocr/ocr.proto

package ocr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OCRRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Langs []string `protobuf:"bytes,1,rep,name=langs,proto3" json:"langs,omitempty"`
	Bytes []byte   `protobuf:"bytes,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
}

func (x *OCRRequest) Reset() {
	*x = OCRRequest{}
	mi := &file_ocr_ocr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCRRequest) ProtoMessage() {}

func (x *OCRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ocr_ocr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCRRequest.ProtoReflect.Descriptor instead.
func (*OCRRequest) Descriptor() ([]byte, []int) {
	return file_ocr_ocr_proto_rawDescGZIP(), []int{0}
}

func (x *OCRRequest) GetLangs() []string {
	if x != nil {
		return x.Langs
	}
	return nil
}

func (x *OCRRequest) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

type OCRResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *OCRResponse) Reset() {
	*x = OCRResponse{}
	mi := &file_ocr_ocr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OCRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OCRResponse) ProtoMessage() {}

func (x *OCRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ocr_ocr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OCRResponse.ProtoReflect.Descriptor instead.
func (*OCRResponse) Descriptor() ([]byte, []int) {
	return file_ocr_ocr_proto_rawDescGZIP(), []int{1}
}

func (x *OCRResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_ocr_ocr_proto protoreflect.FileDescriptor

var file_ocr_ocr_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6f, 0x63, 0x72, 0x2f, 0x6f, 0x63, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x6f, 0x63, 0x72, 0x22, 0x38, 0x0a, 0x0a, 0x4f, 0x43, 0x52, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x6c, 0x61, 0x6e, 0x67, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x22, 0x21,
	0x0a, 0x0b, 0x4f, 0x43, 0x52, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x32, 0x36, 0x0a, 0x0a, 0x4f, 0x43, 0x52, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x28, 0x0a, 0x03, 0x4f, 0x43, 0x52, 0x12, 0x0f, 0x2e, 0x6f, 0x63, 0x72, 0x2e, 0x4f, 0x43, 0x52,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x6f, 0x63, 0x72, 0x2e, 0x4f, 0x43,
	0x52, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x66, 0x75, 0x6e, 0x31, 0x32, 0x35, 0x2f,
	0x74, 0x65, 0x73, 0x73, 0x65, 0x72, 0x61, 0x63, 0x74, 0x2d, 0x67, 0x6f, 0x2f, 0x6f, 0x63, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ocr_ocr_proto_rawDescOnce sync.Once
	file_ocr_ocr_proto_rawDescData = file_ocr_ocr_proto_rawDesc
)

func file_ocr_ocr_proto_rawDescGZIP() []byte {
	file_ocr_ocr_proto_rawDescOnce.Do(func() {
		file_ocr_ocr_proto_rawDescData = protoimpl.X.CompressGZIP(file_ocr_ocr_proto_rawDescData)
	})
	return file_ocr_ocr_proto_rawDescData
}

var file_ocr_ocr_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ocr_ocr_proto_goTypes = []any{
	(*OCRRequest)(nil),  // 0: ocr.OCRRequest
	(*OCRResponse)(nil), // 1: ocr.OCRResponse
}
var file_ocr_ocr_proto_depIdxs = []int32{
	0, // 0: ocr.OCRService.OCR:input_type -> ocr.OCRRequest
	1, // 1: ocr.OCRService.OCR:output_type -> ocr.OCRResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ocr_ocr_proto_init() }
func file_ocr_ocr_proto_init() {
	if File_ocr_ocr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ocr_ocr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ocr_ocr_proto_goTypes,
		DependencyIndexes: file_ocr_ocr_proto_depIdxs,
		MessageInfos:      file_ocr_ocr_proto_msgTypes,
	}.Build()
	File_ocr_ocr_proto = out.File
	file_ocr_ocr_proto_rawDesc = nil
	file_ocr_ocr_proto_goTypes = nil
	file_ocr_ocr_proto_depIdxs = nil
}
